table 'Unemployment Rate'
	lineageTag: dcbb0986-7a17-46c0-b91d-62674ed407f9

	measure 'Texas Rate' = AVERAGE('Unemployment Rate'[Texas])
		lineageTag: 407d0cf7-af06-420f-8246-b7be7a00eff1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: aac07204-b27d-4bcc-b056-fa938ace159c
		summarizeBy: none
		sourceColumn: Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'United States'
		dataType: double
		lineageTag: 98aed41f-06bd-47d6-97dc-3b617c3a62f6
		summarizeBy: sum
		sourceColumn: United States

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Texas
		dataType: double
		lineageTag: ec78f791-29a2-47bd-a339-90b9aa22bb69
		summarizeBy: sum
		sourceColumn: Texas

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Custom
		dataType: string
		lineageTag: 6e2c0021-240d-4a24-9e24-22a53a2e9970
		summarizeBy: none
		sourceColumn: Custom

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 901a426c-f1a1-42a3-a94c-b0da287377ec
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column 'Unemployment Rate'
		dataType: double
		lineageTag: 48132f7e-41f4-4043-96d1-a99abca17499
		summarizeBy: sum
		sourceColumn: Unemployment Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Unemployment Rate' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\marci\Downloads\696_LausCITY2005.xlsx"), null, true),
				    #"Unemployment Rate_Sheet" = Source{[Item="Unemployment Rate",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Unemployment Rate_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"United States", type number}, {"Texas", type number}, {"Abilene", type number}, {"Allen", type number}, {"Alvin", type number}, {"Amarillo", type number}, {"Anna", type number}, {"Arlington", type number}, {"Austin", type number}, {"Balch Springs", type number}, {"Baytown", type number}, {"Beaumont", type number}, {"Bedford", type number}, {"Belton", type number}, {"Big Spring", type number}, {"Brownsville", type number}, {"Bryan", type number}, {"Burleson", type number}, {"Carrollton", type number}, {"Cedar Hill", type number}, {"Cedar Park", type number}, {"Celina", type number}, {"Cibolo", type number}, {"Cleburne", type number}, {"College Station", type number}, {"Colleyville", type number}, {"Conroe", type number}, {"Converse", type number}, {"Coppell", type number}, {"Copperas Cove", type number}, {"Corpus Christi", type number}, {"Corsicana", type number}, {"Dallas", type number}, {"Deer Park", type number}, {"Del Rio", type number}, {"Denison", type number}, {"Denton", type number}, {"DeSoto", type number}, {"Duncanville", type number}, {"Eagle Pass", type number}, {"Edinburg", type number}, {"El Paso", type number}, {"Euless", type number}, {"Farmers Branch", type number}, {"Fate", type number}, {"Flower Mound", type number}, {"Forney", type number}, {"Fort Worth", type number}, {"Friendswood", type number}, {"Frisco", type number}, {"Fulshear", type number}, {"Galveston", type number}, {"Garland", type number}, {"Georgetown", type number}, {"Grand Prairie", type number}, {"Grapevine", type number}, {"Greenville", type number}, {"Haltom City", type number}, {"Harker Heights", type number}, {"Harlingen", type number}, {"Houston", type number}, {"Huntsville", type number}, {"Hurst", type number}, {"Hutto", type number}, {"Irving", type number}, {"Katy", type number}, {"Keller", type number}, {"Kerrville", type number}, {"Killeen", type number}, {"Kingsville", type number}, {"Kyle", type number}, {"La Porte", type number}, {"Lake Jackson", type number}, {"Lancaster", type number}, {"Laredo", type number}, {"League City", type number}, {"Leander", type number}, {"Lewisville", type number}, {"Little Elm", type number}, {"Longview", type number}, {"Lubbock", type number}, {"Lufkin", type number}, {"Mansfield", type number}, {"McAllen", type number}, {"McKinney", type number}, {"Melissa", type number}, {"Mesquite", type number}, {"Midland", type number}, {"Midlothian", type number}, {"Mission", type number}, {"Missouri City", type number}, {"Nacogdoches", type number}, {"New Braunfels", type number}, {"North Richland Hills", type number}, {"Odessa", type number}, {"Paris", type number}, {"Pasadena", type number}, {"Pearland", type number}, {"Pflugerville", type number}, {"Pharr", type number}, {"Plano", type number}, {"Port Arthur", type number}, {"Princeton", type number}, {"Prosper", type number}, {"Richardson", type number}, {"Rockwall", type number}, {"Rosenberg", type number}, {"Round Rock", type number}, {"Rowlett", type number}, {"Royse City", type number}, {"Sachse", type number}, {"Saginaw", type number}, {"San Angelo", type number}, {"San Antonio", type number}, {"San Benito", type number}, {"San Juan", type number}, {"San Marcos", type number}, {"Schertz", type number}, {"Seguin", type number}, {"Sherman", type number}, {"Socorro", type number}, {"Southlake", type number}, {"Sugar Land", type number}, {"Temple", type number}, {"Texarkana", type number}, {"Texas City", type number}, {"The Colony", type number}, {"Tyler", type number}, {"University Park", type number}, {"Victoria", type number}, {"Waco", type number}, {"Waxahachie", type number}, {"Weatherford", type number}, {"Weslaco", type number}, {"Wichita Falls", type number}, {"Wylie", type number}, {"Column138", type any}, {"Column139", type any}, {"Column140", type any}, {"Column141", type any}, {"Column142", type any}, {"Column143", type any}, {"Column144", type any}, {"Column145", type any}, {"Column146", type any}, {"Column147", type any}, {"Column148", type any}, {"Column149", type any}, {"Column150", type any}, {"Column151", type any}, {"Column152", type any}, {"Column153", type any}, {"Column154", type any}, {"Column155", type any}, {"Column156", type any}, {"Column157", type any}, {"Column158", type any}, {"Column159", type any}, {"Column160", type any}, {"Column161", type any}, {"Column162", type any}, {"Column163", type any}, {"Column164", type any}, {"Column165", type any}, {"Column166", type any}, {"Column167", type any}, {"Column168", type any}, {"Column169", type any}, {"Column170", type any}, {"Column171", type any}, {"Column172", type any}, {"Column173", type any}, {"Column174", type any}, {"Column175", type any}, {"Column176", type any}, {"Column177", type any}, {"Column178", type any}, {"Column179", type any}, {"Column180", type any}, {"Column181", type any}, {"Column182", type any}, {"Column183", type any}, {"Column184", type any}, {"Column185", type any}, {"Column186", type any}, {"Column187", type any}, {"Column188", type any}, {"Column189", type any}, {"Column190", type any}, {"Column191", type any}, {"Column192", type any}, {"Column193", type any}, {"Column194", type any}, {"Column195", type any}, {"Column196", type any}, {"Column197", type any}, {"Column198", type any}, {"Column199", type any}, {"Column200", type any}, {"Column201", type any}, {"Column202", type any}, {"Column203", type any}, {"Column204", type any}, {"Column205", type any}, {"Column206", type any}, {"Column207", type any}, {"Column208", type any}, {"Column209", type any}, {"Column210", type any}, {"Column211", type any}, {"Column212", type any}, {"Column213", type any}, {"Column214", type any}, {"Column215", type any}, {"Column216", type any}, {"Column217", type any}, {"Column218", type any}, {"Column219", type any}, {"Column220", type any}, {"Column221", type any}, {"Column222", type any}, {"Column223", type any}, {"Column224", type any}, {"Column225", type any}, {"Column226", type any}, {"Column227", type any}, {"Column228", type any}, {"Column229", type any}, {"Column230", type any}, {"Column231", type any}, {"Column232", type any}, {"Column233", type any}, {"Column234", type any}, {"Column235", type any}, {"Column236", type any}, {"Column237", type any}, {"Column238", type any}, {"Column239", type any}, {"Column240", type any}, {"Column241", type any}, {"Column242", type any}, {"Column243", type any}, {"Column244", type any}, {"Column245", type any}, {"Column246", type any}, {"Column247", type any}, {"Column248", type any}, {"Column249", type any}, {"Column250", type any}, {"Column251", type any}, {"Column252", type any}, {"Column253", type any}, {"Column254", type any}, {"Column255", type any}, {"Column256", type any}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Abilene", "Allen", "Alvin", "Amarillo", "Anna", "Arlington", "Austin", "Balch Springs", "Baytown", "Beaumont", "Bedford", "Belton", "Big Spring", "Bryan", "Burleson", "Carrollton", "Cedar Hill", "Cedar Park", "Celina", "Cibolo", "Cleburne", "College Station", "Colleyville", "Conroe", "Converse", "Coppell", "Copperas Cove", "Corpus Christi", "Corsicana", "Dallas", "Deer Park", "Del Rio", "Denison", "Denton", "DeSoto", "Duncanville", "Eagle Pass", "El Paso", "Euless", "Farmers Branch", "Fate", "Flower Mound", "Forney", "Fort Worth", "Friendswood", "Frisco", "Fulshear", "Galveston", "Garland", "Georgetown", "Grand Prairie", "Grapevine", "Greenville", "Haltom City", "Harker Heights", "Houston", "Huntsville", "Hurst", "Hutto", "Irving", "Katy", "Keller", "Kerrville", "Killeen", "Kingsville", "Kyle", "La Porte", "Lake Jackson", "Lancaster", "Laredo", "League City", "Leander", "Lewisville", "Little Elm", "Longview", "Lubbock", "Lufkin", "Mansfield", "McKinney", "Melissa", "Mesquite", "Midland", "Midlothian", "Missouri City", "Nacogdoches", "New Braunfels", "North Richland Hills", "Odessa", "Paris", "Pasadena", "Pearland", "Pflugerville", "Plano", "Port Arthur", "Princeton", "Prosper", "Richardson", "Rockwall", "Rosenberg", "Round Rock", "Rowlett", "Royse City", "Sachse", "Saginaw", "San Angelo", "San Antonio", "San Marcos", "Schertz", "Seguin", "Sherman", "Socorro", "Southlake", "Sugar Land", "Temple", "Texarkana", "Texas City", "The Colony", "Tyler", "University Park", "Victoria", "Waco", "Waxahachie", "Weatherford", "Wichita Falls", "Wylie", "Column138", "Column139", "Column140", "Column141", "Column142", "Column143", "Column144", "Column145", "Column146", "Column147", "Column148", "Column149", "Column150", "Column151", "Column152", "Column153", "Column154", "Column155", "Column156", "Column157", "Column158", "Column159", "Column160", "Column161", "Column162", "Column163", "Column164", "Column165", "Column166", "Column167", "Column168", "Column169", "Column170", "Column171", "Column172", "Column173", "Column174", "Column175", "Column176", "Column177", "Column178", "Column179", "Column180", "Column181", "Column182", "Column183", "Column184", "Column185", "Column186", "Column187", "Column188", "Column189", "Column190", "Column191", "Column192", "Column193", "Column194", "Column195", "Column196", "Column197", "Column198", "Column199", "Column200", "Column201", "Column202", "Column203", "Column204", "Column205", "Column206", "Column207", "Column208", "Column209", "Column210", "Column211", "Column212", "Column213", "Column214", "Column215", "Column216", "Column217", "Column218", "Column219", "Column220", "Column221", "Column222", "Column223", "Column224", "Column225", "Column226", "Column227", "Column228", "Column229", "Column230", "Column231", "Column232", "Column233", "Column234", "Column235", "Column236", "Column237", "Column238", "Column239", "Column240", "Column241", "Column242", "Column243", "Column244", "Column245", "Column246", "Column247", "Column248", "Column249", "Column250", "Column251", "Column252", "Column253", "Column254", "Column255", "Column256"}),
				    #"Unpivoted Columns" = Table.UnpivotOtherColumns(#"Removed Columns", {"Date", "United States", "Texas"}, "Attribute", "Value"),
				    #"Renamed Columns" = Table.RenameColumns(#"Unpivoted Columns",{{"Attribute", "City"}, {"Value", "Unemployment Rate"}}),
				    #"Added Custom" = Table.AddColumn(#"Renamed Columns", "Custom", each if [City] = "Brownsville" then "Cameron"
				else if [City] = "Harlingen" then "Cameron"
				else if [City] = "San Benito" then "Cameron"
				else if [City] = "Edinburg" then "Hidalgo"
				else if [City] = "McAllen" then "Hidalgo"
				else if [City] = "Mc Allen" then "Hidalgo"
				else if [City] = "Mission" then "Hidalgo"
				else if [City] = "Pharr" then "Hidalgo"
				else if [City] = "San Juan" then "Hidalgo"
				else if [City] = "Weslaco" then "Hidalgo"
				else "Other"),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Custom",{"Date", "United States", "Texas", "Custom", "City", "Unemployment Rate"})
				in
				    #"Reordered Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

